name: intelligent_tutoring_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-214.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  #  state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6


  jwt_decoder: ^2.0.1

  #  code generator
  freezed: ^3.0.3
  freezed_annotation: ^3.0.0
  #  dependency
  get_it: ^7.7.0

  json_serializable: ^6.9.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7

  build_runner: ^2.4.15
  #networking
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  #localization
  easy_localization: ^3.0.7
  intl: ^0.19.0
  webview_flutter: ^4.4.2
  
  #  for splash view
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  go_router: ^14.1.4
  video_player: ^2.9.2

  file_picker: ^8.3.5

  youtube_player_flutter: ^9.1.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Course.PNG
    - assets/hero.svg
    - assets/tt.svg
    - assets/hero.png
    - assets/flutter.svg
    - assets/mysql.svg
    - assets/abc.mp4
    - assets/duolingo.gif
    - assets/duolingo (1).gif
    - assets/tt.gif
    - assets/icons/
    - assets/me.png
